FROM bitnami/spark:3.5.1
USER root
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

ENV APACHE_SPARK_MAJOR_VERSION="3.5" \
    ICEBERG_VERSION="1.9.1" \
    HADOOP_VERSION="3.3.4" \
    AWSJAVASDK_VERSION="1.12.262" \
    SPARK_HOME="/opt/bitnami/spark"

# Guava & drivers DB
RUN curl -L https://repo1.maven.org/maven2/com/google/guava/guava/32.0.1-jre/guava-32.0.1-jre.jar -o ${SPARK_HOME}/jars/guava-32.0.1-jre.jar \
 && curl -L https://jdbc.postgresql.org/download/postgresql-42.2.24.jar -o ${SPARK_HOME}/jars/postgresql-42.2.24.jar \
 && curl -L https://repo1.maven.org/maven2/com/microsoft/sqlserver/mssql-jdbc/12.6.1.jre8/mssql-jdbc-12.6.1.jre8.jar -o ${SPARK_HOME}/jars/mssql-jdbc-12.6.1.jre8.jar

# Iceberg + AWS bundle
RUN curl -L https://repo1.maven.org/maven2/org/apache/iceberg/iceberg-spark-runtime-${APACHE_SPARK_MAJOR_VERSION}_2.12/${ICEBERG_VERSION}/iceberg-spark-runtime-${APACHE_SPARK_MAJOR_VERSION}_2.12-${ICEBERG_VERSION}.jar -o ${SPARK_HOME}/jars/iceberg-spark-runtime-${APACHE_SPARK_MAJOR_VERSION}_2.12-${ICEBERG_VERSION}.jar \
 && curl -L https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/${AWSJAVASDK_VERSION}/aws-java-sdk-bundle-${AWSJAVASDK_VERSION}.jar -o ${SPARK_HOME}/jars/aws-java-sdk-bundle-${AWSJAVASDK_VERSION}.jar \
 && curl -L https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/${HADOOP_VERSION}/hadoop-aws-${HADOOP_VERSION}.jar -o ${SPARK_HOME}/jars/hadoop-aws-${HADOOP_VERSION}.jar \
 && curl -L https://repo1.maven.org/maven2/org/apache/iceberg/iceberg-aws-bundle/${ICEBERG_VERSION}/iceberg-aws-bundle-${ICEBERG_VERSION}.jar -o ${SPARK_HOME}/jars/iceberg-aws-bundle-${ICEBERG_VERSION}.jar

USER 1001