version: "3.3"

services:
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    container_name: minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio-data:/data

  create-bucket:
    image: minio/mc:latest
    container_name: create-bucket
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      mc alias set local ${MINIO_ENDPOINT} ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD} && mc mb -p local/${MINIO_BUCKET} || true
      until (/usr/bin/mc config host add minio ${MINIO_ENDPOINT} ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD}) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc rm -r --force minio/warehouse;
      /usr/bin/mc mb minio/warehouse;
      /usr/bin/mc policy set public minio/warehouse;
      tail -f /dev/null
      "

  spark-master:
    build:
      context: .
      dockerfile: Dockerfile.spark
    container_name: spark-master
    ports:
      - "4040:4040"
      - "7077:7077"
    depends_on:
      - rest
      - minio
    environment:
      SPARK_NO_DAEMONIZE: "yes"
      SPARK_LOCAL_IP: spark-master
    command: bin/spark-class org.apache.spark.deploy.master.Master
 
    #command: ["/bin/bash", "-lc", "sleep infinity"]

  jupyter:
    image: jupyter/pyspark-notebook:latest
    container_name: jupyter
    depends_on:
      - spark-master
      - rest
      - minio
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      JUPYTER_TOKEN: ""           # désactive le token
      JUPYTER_PASSWORD: ""        # désactive le mot de passe
    command: start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''

  rest:
    image: tabulario/iceberg-rest
    container_name: iceberg-rest
    ports:
      - 8181:8181
    environment:
      - AWS_ACCESS_KEY_ID=${MINIO_ROOT_USER}
      - AWS_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}
      - AWS_REGION=us-east-1
      - CATALOG_WAREHOUSE=s3://${MINIO_BUCKET}/ 
      - CATALOG_IO__IMPL=org.apache.iceberg.aws.s3.S3FileIO
      - CATALOG_S3_ENDPOINT=${MINIO_ENDPOINT}

  trino:
    image: trinodb/trino:latest
    container_name: trino
    environment:
      - TRINO_USER=admin
      - TRINO_PASSWORD=admin
    ports:
      - 8080:8080
    depends_on:
      - rest
      - minio
    volumes:
      - ./trino/iceberg.properties:/etc/trino/catalog/iceberg.properties


networks:
  default:
    name: iceberg-net