
version: "3.3"
services:
  superset:
    build:
      context: ./superset
    container_name: superset
    networks:
      - iceberg_net
    environment:
      - ADMIN_USERNAME=admin
      - ADMIN_EMAIL=admin@superset.com
      - ADMIN_PASSWORD=admin
    ports:
      - 8088:8088
    depends_on:
      trino:
        condition: service_started