version: "3.3"

services:
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    container_name: minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      AWS_REGION: eu-west-1
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      iceberg_net:
        aliases:
          - warehouse.minio
    volumes:
      - ./minio-data:/data

  create-bucket:
    image: minio/mc:latest
    container_name: create-bucket
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      AWS_REGION: eu-west-1
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set minio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD}) \
        do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc rm -r --force minio/warehouse;
      /usr/bin/mc mb minio/warehouse;
      /usr/bin/mc anonymous set public minio/warehouse;
      /usr/bin/mc rm -r --force minio/raw;
      /usr/bin/mc mb minio/raw;
      /usr/bin/mc anonymous set public minio/raw;
      tail -f /dev/null
      "
    networks:
      iceberg_net:

  postgres:
    image: postgres:latest
    container_name: postgres
    networks:
      - iceberg_net
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db-scripts:/docker-entrypoint-initdb.d  # <--- scripts auto-exécutés

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5

  spark-master:
    build:
      context: .
      dockerfile: Dockerfile.spark
    container_name: spark-master
    ports:
      - "9090:9090"
      - "7077:7077"
      - "8888:8888"
    depends_on:
      - rest
      - minio
    volumes:
      - ./notebooks:/home/jupyter/work
    networks:
      iceberg_net:
        aliases:
          - spark-master
    environment:
      SPARK_MODE: master
      SPARK_MASTER_WEBUI_PORT: 9090

  trino:
    image: trinodb/trino:latest
    container_name: trino
    environment:
      TRINO_USER: admin
      TRINO_PASSWORD: admin
    ports:
      - 8080:8080
    depends_on:
      - rest
      - minio
    volumes:
      - ./trino/iceberg.properties:/etc/trino/catalog/iceberg.properties
    networks:
      iceberg_net:
        aliases:
          - trino

  rest:
    image: rmeftah/iceberg-rest-catalog:latest
    container_name: rest
    restart: always
    environment:
      CATALOG_NAME: WAREHOUSE
      WAREHOUSE_LOCATION: s3a://WAREHOUSE/wh
      IMPL: org.apache.iceberg.JDBC_JdbcCatalog
      REST_PORT: 8181
      IO_IMPL: org.apache.iceberg.aws.s3.S3FileIO
      S3_ENDPOINT: http://minio:9000
      URI: jdbc:postgresql://postgres:5432/warehouse
      JDBC_USER: postgres
      JDBC_PASSWORD: postgres
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      AWS_REGION: us-east-1
    ports:
      - "8181:8181"
    depends_on:
      - postgres
      - minio
    networks:
      - iceberg_net

networks:
  iceberg_net:
    driver: bridge

volumes:
  postgres-data:


